// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emkigybfcuelnfxpztod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVta2lneWJmY3VlbG5meHB6dG9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzAyNzUsImV4cCI6MjA1ODQwNjI3NX0.LofxlzpOjTv62u2mJnTo9pff6Hgeudr78Y8lJtsJ4MY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);